/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "HeyzapMarmalade.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*HeyzapMarmaladeRegister_t)(HeyzapMarmaladeCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*HeyzapMarmaladeUnRegister_t)(HeyzapMarmaladeCallback cbid, s3eCallback fn);
typedef       void(*loadHeyzap_t)(const char* appId, const char* appURL, bool androidToast);
typedef       void(*checkinHeyzap_t)();
typedef       void(*checkinHeyzapWithMessage_t)(const char* message);

/**
 * struct that gets filled in by HeyzapMarmaladeRegister
 */
typedef struct HeyzapMarmaladeFuncs
{
    HeyzapMarmaladeRegister_t m_HeyzapMarmaladeRegister;
    HeyzapMarmaladeUnRegister_t m_HeyzapMarmaladeUnRegister;
    loadHeyzap_t m_loadHeyzap;
    checkinHeyzap_t m_checkinHeyzap;
    checkinHeyzapWithMessage_t m_checkinHeyzapWithMessage;
} HeyzapMarmaladeFuncs;

static HeyzapMarmaladeFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xddddfc7a, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: HeyzapMarmalade");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xddddfc7a, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool HeyzapMarmaladeAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult HeyzapMarmaladeRegister(HeyzapMarmaladeCallback cbid, s3eCallback fn, void* userData)
{
    IwTrace(HEYZAPMARMALADE_VERBOSE, ("calling HeyzapMarmalade[0] func: HeyzapMarmaladeRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_HeyzapMarmaladeRegister(cbid, fn, userData);
}

s3eResult HeyzapMarmaladeUnRegister(HeyzapMarmaladeCallback cbid, s3eCallback fn)
{
    IwTrace(HEYZAPMARMALADE_VERBOSE, ("calling HeyzapMarmalade[1] func: HeyzapMarmaladeUnRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_HeyzapMarmaladeUnRegister(cbid, fn);
}

void loadHeyzap(const char* appId, const char* appURL, bool androidToast)
{
    IwTrace(HEYZAPMARMALADE_VERBOSE, ("calling HeyzapMarmalade[2] func: loadHeyzap"));

    if (!_extLoad())
        return;

    g_Ext.m_loadHeyzap(appId, appURL, androidToast);
}

void checkinHeyzap()
{
    IwTrace(HEYZAPMARMALADE_VERBOSE, ("calling HeyzapMarmalade[3] func: checkinHeyzap"));

    if (!_extLoad())
        return;

    g_Ext.m_checkinHeyzap();
}

void checkinHeyzapWithMessage(const char* message)
{
    IwTrace(HEYZAPMARMALADE_VERBOSE, ("calling HeyzapMarmalade[4] func: checkinHeyzapWithMessage"));

    if (!_extLoad())
        return;

    g_Ext.m_checkinHeyzapWithMessage(message);
}
